sudo: required
services:
  - docker

before_install:
  - docker build -t abhiit89/client-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhiit89/client-tests npm test -- --coverage

after_success:
  - docker build -t abhiit89/fib-client ./client
  - docker build -t abhiit89/fib-nginx ./nginx
  - docker build -t abhiit89/fib-server ./server
  - docker build -t abhiit89/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push abhiit89/fib-client
  - docker push abhiit89/fib-nginx
  - docker push abhiit89/fib-server
  - docker push abhiit89/fib-worker